name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: 0xgitgat
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push to Output branch
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: "Generated snake animation"
